version: '3.5'

services:
  build:
    build:
      context: packages/api
      target: development
    command: >
      sh -c "yarn install --only=development"
    volumes:
      - .:/usr/src/app
    networks:
      - nestjs-network

  service:
    container_name: ideal-service
    build:
      context: packages/api
      target: development
    command: yarn run start:debug
    ports:
      - 3002:3002
    networks:
      - nestjs-network
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - APP_PORT=3002
      - DB_HOSTNAME=ideal_postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=changeme
      - DB_NAME=postgres
    restart: unless-stopped

  postgres:
    container_name: ideal_postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - nestjs-network
    restart: unless-stopped

  pgadmin:
    container_name: ideal_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin

    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - nestjs-network
    restart: unless-stopped

networks:
  nestjs-network:
    driver: bridge

volumes:
  postgres:
  pgadmin:
