name: ideal-funicular build job

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  buildAndTest:

    runs-on: node:16-alpine3.12

    steps:
    - uses: actions/checkout@v2

    - name: install
      run: |
        cd packages/api
        yarn install
        cd ../..
        cd packages/policy-app
        yarn install

    - name: test
      run: |
        cd packages/api
        yarn run test
        cd ../..
        cd packages/policy-app
        yarn run test


