name: ideal-funicular build job

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  buildAndTest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: node install
      run: |
        npm i
        npm run test
        npm run lint

  start:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: node install
      run: |
        npm i
        npm run start

  deploy:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: docker build
      run: docker build . --file Dockerfile --tag amarflybot/ideal-funicular:$(date +%s)
    
