name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Print latest message
      run: echo ${{ github.event.head_commit.message }}

    - name: node install and test
      run: |
        npm i
        npm run test
        npm run lint

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag amarflybot/ideal-funicular:$(date +%s)
    
